name = "MA4N1_Platonic_Solids"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«MA4N1_Platonic_Solids»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "«MA4N1_Platonic_Solids»"
